--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    start_date date,
    delivery_date date,
    sales_id bigint,
    index smallint,
    trello_card_id text,
    -- The sales users this deal is assigned to. A deal is only visible to its
    -- assignees (RLS in 05_policies.sql), so this is the access-control list for
    -- the card: shared work gets several assignees, private cards just one.
    -- Defaults to the owner (sales_id) on insert via set_sales_id_default.
    assignee_ids bigint[] not null default '{}'::bigint[],
    -- "In de wacht" IS a kanban column (stage 'on-hold'). This flag is DERIVED
    -- from that stage by the sync_deal_on_hold trigger (on_hold := stage =
    -- 'on-hold') and drives the badge on the card; a direct write to it is
    -- overwritten by the trigger on the next save.
    on_hold boolean not null default false,
    -- Internal work (Happr product, Marketingbende/Online Matters own projects)
    -- vs external client work. Drives the Intern/Extern board filter.
    is_internal boolean not null default false,
    -- Set the first time the deal's Trello card moves into "Klaar", so the
    -- team-lead notification is sent at most once even though Trello webhooks
    -- are delivered at-least-once and retried.
    won_notified_at timestamp with time zone,
    moneybird_estimate_id text,
    moneybird_estimate_status text,
    moneybird_estimate_claimed_at timestamp with time zone,
    moneybird_estimate_created_by bigint,
    moneybird_estimate_error text,
    -- The Moneybird administration the document was created in. Connections are
    -- per user since the per-user Moneybird integration, so the administration
    -- differs per creator; the deep link in the UI needs it.
    moneybird_estimate_administration_id text,
    moneybird_invoice_id text,
    moneybird_invoice_status text,
    moneybird_invoice_claimed_at timestamp with time zone,
    moneybird_invoice_created_by bigint,
    moneybird_invoice_error text,
    moneybird_invoice_administration_id text,
    -- Whether the deal's amount is a monthly recurring fee ('maandelijks', e.g.
    -- an SEO subscription) or a single one-off project fee ('eenmalig', e.g. a
    -- webshop build). Drives the revenue dashboard (MRR vs one-off). Null when
    -- unknown / not applicable (Happr and other non-billable cards).
    revenue_period text,
    constraint deals_moneybird_estimate_status_check check (moneybird_estimate_status in ('pending', 'completed', 'failed')),
    constraint deals_moneybird_invoice_status_check check (moneybird_invoice_status in ('pending', 'completed', 'failed')),
    constraint deals_revenue_period_check check (revenue_period in ('maandelijks', 'eenmalig'))
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    partij text not null default 'marketingbende'
        check (partij in ('online_matters', 'marketingbende', 'groeien_met_ads'))
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    -- A task is attached to a contact, a deal, or both. Trello-synced deal
    -- steps have no contact, so contact_id is nullable; the check below keeps
    -- every task anchored to at least one of the two.
    contact_id bigint,
    deal_id bigint,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint,
    -- Where the task originated: a person ('manual'), a mirrored Trello
    -- checklist item ('trello'), or the CRM's next-action guard ('auto').
    -- Trello-sourced tasks are kept in sync with, and written back to, their card.
    source text not null default 'manual',
    -- The Trello checklist item this task mirrors (null for manual tasks). Used
    -- as the idempotency key for the sync and to write completions back.
    trello_checkitem_id text,
    constraint tasks_source_check check (source in ('manual', 'trello', 'auto')),
    constraint tasks_contact_or_deal_check
        check (contact_id is not null or deal_id is not null)
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

-- Per-user Moneybird connection. Each CRM user links their OWN Moneybird
-- administration with a personal API token. The token is encrypted with
-- AES-256-GCM by the moneybird_connection edge function (key: the
-- MONEYBIRD_ENC_KEY function secret) before it is stored, and is NEVER
-- readable by client roles (see 06_grants.sql); only the edge functions
-- (service role) decrypt it.
create table public.moneybird_connections (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    administration_id text not null,
    -- Display name of the administration at connect time (cosmetic, shown in
    -- the profile UI; the id is the source of truth).
    administration_name text not null default '',
    api_token_encrypted text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create unique index uq__moneybird_connections__sales_id on public.moneybird_connections using btree (sales_id);

-- Cache of the Moneybird contact created for a CRM company, PER administration.
-- A Moneybird contact id is only valid inside the administration it was created
-- in, and every user connects their own administration, so one company can map
-- to a different contact per administration. Written exclusively by the
-- moneybird edge functions (service role).
create table public.moneybird_company_contacts (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    administration_id text not null,
    contact_id text not null,
    created_at timestamp with time zone not null default now()
);

create unique index uq__moneybird_company_contacts__company_administration
    on public.moneybird_company_contacts using btree (company_id, administration_id);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deals
    add constraint deals_moneybird_estimate_created_by_fkey foreign key (moneybird_estimate_created_by) references public.sales(id);

alter table public.deals
    add constraint deals_moneybird_invoice_created_by_fkey foreign key (moneybird_invoice_created_by) references public.sales(id);

-- stage must be a known pipeline value (five kanban stages + 'lost'); NOT VALID
-- so it only guards future writes, never rejects a pre-existing row.
alter table public.deals
    add constraint deals_stage_check check (stage in ('informatie-pipeline', 'bezig', 'on-hold', 'facturatie-live', 'won', 'lost')) not valid;

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.moneybird_connections
    add constraint moneybird_connections_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.moneybird_company_contacts
    add constraint moneybird_company_contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete set null not valid;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

-- Idempotency ledger for the Resend inbound-email webhook. Resend/Svix deliver
-- at-least-once, so a redelivered or retried event must not re-process the same
-- mail (which would create duplicate contact/deal notes). The webhook claims
-- an email_id here before processing; a conflicting insert means "already
-- handled". Only the edge function (service_role) touches it.
create table public.inbound_email_events (
    email_id text primary key,
    processed_at timestamp with time zone not null default now()
);

-- Durable health history for external integrations. Edge functions create and
-- finish these rows; authenticated CRM users only read them on the dashboard.
-- Keeping the last runs in Postgres makes failures visible after a page reload
-- instead of only showing a temporary toast to the person who pressed sync.
create table public.integration_runs (
    id bigint generated by default as identity primary key,
    integration text not null check (length(trim(integration)) > 0),
    run_kind text not null check (run_kind in ('manual', 'backfill')),
    status text not null check (status in ('running', 'success', 'partial', 'failed')),
    started_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    duration_ms integer check (duration_ms is null or duration_ms >= 0),
    items_processed integer not null default 0 check (items_processed >= 0),
    failed_count integer not null default 0 check (failed_count >= 0),
    summary jsonb not null default '{}'::jsonb,
    error text
);

create index integration_runs_integration_started_idx
    on public.integration_runs using btree (integration, started_at desc);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index tasks_sales_id_due_date_idx on public.tasks using btree (sales_id, due_date);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create index tasks_contact_id_idx on public.tasks using btree (contact_id);
create index companies_sales_id_idx on public.companies using btree (sales_id);
create index contacts_sales_id_idx on public.contacts using btree (sales_id);
create index contact_notes_sales_id_idx on public.contact_notes using btree (sales_id);
create index deal_notes_sales_id_idx on public.deal_notes using btree (sales_id);
create index deals_sales_id_idx on public.deals using btree (sales_id);
create index deals_moneybird_estimate_created_by_idx on public.deals using btree (moneybird_estimate_created_by);
create index deals_moneybird_invoice_created_by_idx on public.deals using btree (moneybird_invoice_created_by);
create index contacts_email_jsonb_idx on public.contacts using gin (email_jsonb);
create index deals_active_stage_closing_idx on public.deals using btree (stage, expected_closing_date) where (archived_at is null);
create index tasks_open_due_date_idx on public.tasks using btree (due_date) where (done_date is null);
-- The activity_log view is queried as one date-descending read model. These
-- source indexes let PostgreSQL satisfy each UNION ALL branch without scanning
-- and sorting every source table for the five newest dashboard events.
create index companies_activity_date_idx on public.companies using btree (created_at desc);
create index contacts_activity_date_idx on public.contacts using btree (first_seen desc);
create index contact_notes_activity_date_idx on public.contact_notes using btree (date desc);
create index deals_activity_date_idx on public.deals using btree (created_at desc);
create index deal_notes_activity_date_idx on public.deal_notes using btree (date desc);
create index contacts_company_activity_idx on public.contacts using btree (company_id, first_seen desc);
create index deals_company_activity_idx on public.deals using btree (company_id, created_at desc);
create index contact_notes_contact_activity_idx on public.contact_notes using btree (contact_id, date desc);
create index deal_notes_deal_activity_idx on public.deal_notes using btree (deal_id, date desc);
create unique index uq__tasks__trello_checkitem_id on public.tasks using btree (trello_checkitem_id) where (trello_checkitem_id is not null);
create unique index uq__deals__trello_card_id on public.deals using btree (trello_card_id) where (trello_card_id is not null);
create unique index uq__deals__moneybird_estimate_id on public.deals using btree (moneybird_estimate_id) where (moneybird_estimate_id is not null);
create unique index uq__deals__moneybird_invoice_id on public.deals using btree (moneybird_invoice_id) where (moneybird_invoice_id is not null);
