--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    moneybird_contact_id text
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    start_date date,
    delivery_date date,
    sales_id bigint,
    index smallint,
    trello_card_id text,
    moneybird_estimate_id text,
    moneybird_estimate_status text,
    moneybird_estimate_claimed_at timestamp with time zone,
    moneybird_estimate_created_by bigint,
    moneybird_estimate_error text,
    moneybird_invoice_id text,
    moneybird_invoice_status text,
    moneybird_invoice_claimed_at timestamp with time zone,
    moneybird_invoice_created_by bigint,
    moneybird_invoice_error text,
    constraint deals_moneybird_estimate_status_check check (moneybird_estimate_status in ('pending', 'completed', 'failed')),
    constraint deals_moneybird_invoice_status_check check (moneybird_invoice_status in ('pending', 'completed', 'failed'))
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    partij text not null default 'marketingbende'
        check (partij in ('online_matters', 'marketingbende', 'groeien_met_ads'))
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    -- A task is attached to a contact, a deal, or both. Trello-synced deal
    -- steps have no contact, so contact_id is nullable; the check below keeps
    -- every task anchored to at least one of the two.
    contact_id bigint,
    deal_id bigint,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint,
    -- Where the task originated: a person created it ('manual') or it mirrors a
    -- Trello checklist item ('trello'). Trello-sourced tasks are kept in sync
    -- with, and written back to, their card.
    source text not null default 'manual',
    -- The Trello checklist item this task mirrors (null for manual tasks). Used
    -- as the idempotency key for the sync and to write completions back.
    trello_checkitem_id text,
    constraint tasks_source_check check (source in ('manual', 'trello')),
    constraint tasks_contact_or_deal_check
        check (contact_id is not null or deal_id is not null)
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deals
    add constraint deals_moneybird_estimate_created_by_fkey foreign key (moneybird_estimate_created_by) references public.sales(id);

alter table public.deals
    add constraint deals_moneybird_invoice_created_by_fkey foreign key (moneybird_invoice_created_by) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete set null not valid;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index tasks_sales_id_due_date_idx on public.tasks using btree (sales_id, due_date);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create unique index uq__tasks__trello_checkitem_id on public.tasks using btree (trello_checkitem_id) where (trello_checkitem_id is not null);
create unique index uq__deals__trello_card_id on public.deals using btree (trello_card_id) where (trello_card_id is not null);
create unique index uq__deals__moneybird_estimate_id on public.deals using btree (moneybird_estimate_id) where (moneybird_estimate_id is not null);
create unique index uq__deals__moneybird_invoice_id on public.deals using btree (moneybird_invoice_id) where (moneybird_invoice_id is not null);
create unique index uq__companies__moneybird_contact_id on public.companies using btree (moneybird_contact_id) where (moneybird_contact_id is not null);
