create table public.inzyte_links (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    company_id bigint,
    website_url text,
    inzyte_user_id uuid not null,
    ga4_connection_id uuid,
    ga4_connection_name text,
    ga4_property_id text,
    ga4_property_name text,
    gsc_site_url text,
    gbp_account_id text,
    gbp_location_id text,
    gbp_location_name text,
    ads_customer_id text,
    ads_account_name text,
    ads_login_customer_id text,
    created_by bigint,
    last_verified_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint inzyte_links_ga4_property_id_check
        check (ga4_property_id is null or ga4_property_id ~ '^[0-9]+$'),
    constraint inzyte_links_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade,
    constraint inzyte_links_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete set null,
    constraint inzyte_links_created_by_fkey foreign key (created_by) references public.sales(id) on update cascade on delete set null
);

create unique index uq__inzyte_links__deal_id
    on public.inzyte_links using btree (deal_id);
create index inzyte_links_company_id_idx
    on public.inzyte_links using btree (company_id);

create table public.inzyte_runs (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    inzyte_link_id bigint,
    action text not null check (length(trim(action)) > 0),
    status text not null check (status in ('running', 'success', 'failed')),
    date_start date,
    date_end date,
    requested_by bigint,
    started_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    result jsonb,
    summary jsonb not null default '{}'::jsonb,
    error text,
    constraint inzyte_runs_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade,
    constraint inzyte_runs_link_id_fkey foreign key (inzyte_link_id) references public.inzyte_links(id) on update cascade on delete set null,
    constraint inzyte_runs_requested_by_fkey foreign key (requested_by) references public.sales(id) on update cascade on delete set null
);

create index inzyte_runs_deal_started_idx
    on public.inzyte_runs using btree (deal_id, started_at desc);
create index inzyte_runs_link_started_idx
    on public.inzyte_runs using btree (inzyte_link_id, started_at desc);

alter table public.inzyte_links enable row level security;
alter table public.inzyte_runs enable row level security;

create policy "Enable read access for visible Inzyte assignments" on public.inzyte_links
    for select to authenticated using (deal_id in (select id from public.deals));
create policy "Enable read access for visible Inzyte runs" on public.inzyte_runs
    for select to authenticated using (deal_id in (select id from public.deals));

grant all on table public.inzyte_links to service_role;
revoke all on table public.inzyte_links from anon, authenticated;
grant select on table public.inzyte_links to authenticated;

grant all on table public.inzyte_runs to service_role;
revoke all on table public.inzyte_runs from anon, authenticated;
grant select on table public.inzyte_runs to authenticated;

grant all on sequence public.inzyte_links_id_seq to service_role;
revoke all on sequence public.inzyte_links_id_seq from anon, authenticated;
grant all on sequence public.inzyte_runs_id_seq to service_role;
revoke all on sequence public.inzyte_runs_id_seq from anon, authenticated;
