-- Durable evidence for recurring SEO work. The tasks table only represents
-- today's checklist state and is deliberately reset for monthly assignments;
-- this append-only journal preserves what was completed in each month.
create table public.deal_task_completions (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    task_id bigint,
    completion_month date not null,
    completed_at timestamp with time zone not null,
    task_text text not null,
    task_type text,
    task_source text,
    trello_checkitem_id text,
    completed_by bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_task_completions_deal_id_fkey
        foreign key (deal_id) references public.deals(id)
        on update cascade on delete cascade,
    constraint deal_task_completions_task_id_fkey
        foreign key (task_id) references public.tasks(id)
        on update cascade on delete set null,
    constraint deal_task_completions_completed_by_fkey
        foreign key (completed_by) references public.sales(id)
        on update cascade on delete set null,
    constraint deal_task_completions_month_start_check
        check (completion_month = date_trunc('month', completion_month)::date),
    constraint deal_task_completions_text_check
        check (length(trim(task_text)) > 0)
);

create unique index uq__deal_task_completions__task_month
    on public.deal_task_completions using btree (task_id, completion_month)
    where task_id is not null;
create index deal_task_completions_deal_completed_idx
    on public.deal_task_completions using btree (deal_id, completed_at desc);
create index deal_task_completions_completed_by_idx
    on public.deal_task_completions using btree (completed_by);

create or replace function private.capture_deal_task_completion()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.deal_id is null or new.done_date is null then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.done_date is not null then
    return new;
  end if;

    insert into public.deal_task_completions (
      deal_id,
      task_id,
      completion_month,
      completed_at,
      task_text,
      task_type,
      task_source,
      trello_checkitem_id,
      completed_by
    ) values (
      new.deal_id,
      new.id,
      date_trunc('month', new.done_date at time zone 'Europe/Amsterdam')::date,
      new.done_date,
      coalesce(nullif(trim(new.text), ''), 'Werkzaamheid zonder omschrijving'),
      new.type,
      new.source,
      new.trello_checkitem_id,
      new.sales_id
    )
    on conflict (task_id, completion_month) where task_id is not null
    do update set
      completed_at = excluded.completed_at,
      task_text = excluded.task_text,
      task_type = excluded.task_type,
      task_source = excluded.task_source,
      trello_checkitem_id = excluded.trello_checkitem_id,
      completed_by = excluded.completed_by;
  return new;
end;
$function$;

create trigger capture_deal_task_completion_trigger
after insert or update of done_date on public.tasks
for each row execute function private.capture_deal_task_completion();

-- Preserve the currently completed checklist state as the first baseline.
insert into public.deal_task_completions (
  deal_id,
  task_id,
  completion_month,
  completed_at,
  task_text,
  task_type,
  task_source,
  trello_checkitem_id,
  completed_by
)
select
  task.deal_id,
  task.id,
  date_trunc('month', task.done_date at time zone 'Europe/Amsterdam')::date,
  task.done_date,
  coalesce(nullif(trim(task.text), ''), 'Werkzaamheid zonder omschrijving'),
  task.type,
  task.source,
  task.trello_checkitem_id,
  task.sales_id
from public.tasks as task
where task.deal_id is not null and task.done_date is not null
on conflict (task_id, completion_month) where task_id is not null do nothing;

-- One immutable data snapshot per assignment and reporting month. Regenerating
-- a draft replaces that month's snapshot; a final report remains available in
-- the assignment history and can still be explicitly regenerated by the user.
create table public.seo_monthly_reports (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    company_id bigint,
    reporting_month date not null,
    current_start date not null,
    current_end date not null,
    previous_start date not null,
    previous_end date not null,
    data_through date,
    status text not null default 'draft',
    title text not null,
    client_summary text,
    work_summary text,
    next_steps text,
    report_data jsonb not null default '{}'::jsonb,
    headline_metrics jsonb not null default '[]'::jsonb,
    current_work_count integer not null default 0,
    all_time_work_count integer not null default 0,
    generated_by bigint,
    generated_at timestamp with time zone not null default now(),
    finalized_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint seo_monthly_reports_deal_id_fkey
        foreign key (deal_id) references public.deals(id)
        on update cascade on delete cascade,
    constraint seo_monthly_reports_company_id_fkey
        foreign key (company_id) references public.companies(id)
        on update cascade on delete set null,
    constraint seo_monthly_reports_generated_by_fkey
        foreign key (generated_by) references public.sales(id)
        on update cascade on delete set null,
    constraint seo_monthly_reports_status_check
        check (status in ('draft', 'final')),
    constraint seo_monthly_reports_month_start_check
        check (reporting_month = date_trunc('month', reporting_month)::date),
    constraint seo_monthly_reports_current_range_check
        check (current_start <= current_end),
    constraint seo_monthly_reports_previous_range_check
        check (previous_start <= previous_end),
    constraint seo_monthly_reports_work_counts_check
        check (current_work_count >= 0 and all_time_work_count >= current_work_count)
);

create unique index uq__seo_monthly_reports__deal_month
    on public.seo_monthly_reports using btree (deal_id, reporting_month);
create index seo_monthly_reports_deal_generated_idx
    on public.seo_monthly_reports using btree (deal_id, reporting_month desc, generated_at desc);
create index seo_monthly_reports_company_month_idx
    on public.seo_monthly_reports using btree (company_id, reporting_month desc);
create index seo_monthly_reports_generated_by_idx
    on public.seo_monthly_reports using btree (generated_by);

-- Moneybird's CRM creation status is not the same thing as the document's live
-- lifecycle (concept, verzonden, geaccepteerd, betaald, te laat, enz.). Keep the
-- last verified Moneybird state separately so the assignment can show both.
alter table public.deals
  add column moneybird_estimate_live_state text,
  add column moneybird_estimate_checked_at timestamp with time zone,
  add column moneybird_invoice_live_state text,
  add column moneybird_invoice_checked_at timestamp with time zone;

alter table public.deal_task_completions enable row level security;
alter table public.seo_monthly_reports enable row level security;

create policy "Enable read access for visible task completion history"
  on public.deal_task_completions
  for select to authenticated
  using (public.is_active_crm_user() and deal_id in (select id from public.deals));

create policy "Enable read access for visible SEO month reports"
  on public.seo_monthly_reports
  for select to authenticated
  using (public.is_active_crm_user() and deal_id in (select id from public.deals));

revoke all on table public.deal_task_completions from anon, authenticated;
grant select on table public.deal_task_completions to authenticated;
grant all on table public.deal_task_completions to service_role;
revoke all on sequence public.deal_task_completions_id_seq from anon, authenticated;
grant all on sequence public.deal_task_completions_id_seq to service_role;

revoke all on table public.seo_monthly_reports from anon, authenticated;
grant select on table public.seo_monthly_reports to authenticated;
grant all on table public.seo_monthly_reports to service_role;
revoke all on sequence public.seo_monthly_reports_id_seq from anon, authenticated;
grant all on sequence public.seo_monthly_reports_id_seq to service_role;

revoke all on function private.capture_deal_task_completion() from public, anon, authenticated;
grant execute on function private.capture_deal_task_completion() to service_role;
