-- Durable Trello synchronization history for the CRM integration dashboard.
create table if not exists public.integration_runs (
  id bigint generated by default as identity primary key,
  integration text not null check (length(trim(integration)) > 0),
  run_kind text not null check (run_kind in ('manual', 'backfill')),
  status text not null check (status in ('running', 'success', 'partial', 'failed')),
  started_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  items_processed integer not null default 0 check (items_processed >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  summary jsonb not null default '{}'::jsonb,
  error text
);

create index if not exists integration_runs_integration_started_idx
  on public.integration_runs using btree (integration, started_at desc);

alter table public.integration_runs enable row level security;

drop policy if exists "Enable read access for active CRM users" on public.integration_runs;
create policy "Enable read access for active CRM users"
  on public.integration_runs for select to authenticated
  using (public.is_active_crm_user());

grant all on table public.integration_runs to service_role;
revoke all on table public.integration_runs from anon, authenticated;
grant select on table public.integration_runs to authenticated;

grant all on sequence public.integration_runs_id_seq to service_role;
revoke all on sequence public.integration_runs_id_seq from anon, authenticated;
