drop view if exists "public"."activity_log";

drop view if exists "public"."companies_summary";

drop view if exists "public"."contacts_summary";

drop index if exists "public"."uq__companies__moneybird_contact_id";


  create table "public"."moneybird_company_contacts" (
    "id" bigint generated by default as identity not null,
    "company_id" bigint not null,
    "administration_id" text not null,
    "contact_id" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."moneybird_company_contacts" enable row level security;


  create table "public"."moneybird_connections" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "administration_id" text not null,
    "administration_name" text not null default '',
    "api_token_encrypted" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."moneybird_connections" enable row level security;

-- DATA MIGRATION (manually added): every Moneybird contact cached on companies
-- so far was created in the original shared Marketingbende administration
-- (478715071487280295), the only administration the integration knew before it
-- became per-user. Move those ids into the new per-administration cache BEFORE
-- the column is dropped.
insert into public.moneybird_company_contacts (company_id, administration_id, contact_id)
select id, '478715071487280295', moneybird_contact_id
from public.companies
where moneybird_contact_id is not null;

alter table "public"."companies" drop column "moneybird_contact_id";

alter table "public"."deals" add column "moneybird_estimate_administration_id" text;

alter table "public"."deals" add column "moneybird_invoice_administration_id" text;

-- DATA MIGRATION (manually added): all existing Moneybird documents were
-- created in the shared Marketingbende administration; stamp them so the
-- per-user deep links in the UI keep working.
update public.deals
set moneybird_estimate_administration_id = '478715071487280295'
where moneybird_estimate_id is not null;

update public.deals
set moneybird_invoice_administration_id = '478715071487280295'
where moneybird_invoice_id is not null;

CREATE UNIQUE INDEX moneybird_company_contacts_pkey ON public.moneybird_company_contacts USING btree (id);

CREATE UNIQUE INDEX moneybird_connections_pkey ON public.moneybird_connections USING btree (id);

CREATE UNIQUE INDEX uq__moneybird_company_contacts__company_administration ON public.moneybird_company_contacts USING btree (company_id, administration_id);

CREATE UNIQUE INDEX uq__moneybird_connections__sales_id ON public.moneybird_connections USING btree (sales_id);

alter table "public"."moneybird_company_contacts" add constraint "moneybird_company_contacts_pkey" PRIMARY KEY using index "moneybird_company_contacts_pkey";

alter table "public"."moneybird_connections" add constraint "moneybird_connections_pkey" PRIMARY KEY using index "moneybird_connections_pkey";

alter table "public"."moneybird_company_contacts" add constraint "moneybird_company_contacts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."moneybird_company_contacts" validate constraint "moneybird_company_contacts_company_id_fkey";

alter table "public"."moneybird_connections" add constraint "moneybird_connections_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."moneybird_connections" validate constraint "moneybird_connections_sales_id_fkey";

create or replace view "public"."activity_log" as  SELECT (('company.'::text || c.id) || '.created'::text) AS id,
    'company.created'::text AS type,
    c.created_at AS date,
    c.id AS company_id,
    c.sales_id,
    to_json(c.*) AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.companies c
UNION ALL
 SELECT (('contact.'::text || co.id) || '.created'::text) AS id,
    'contact.created'::text AS type,
    co.first_seen AS date,
    co.company_id,
    co.sales_id,
    NULL::json AS company,
    to_json(co.*) AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.contacts co
UNION ALL
 SELECT (('contactNote.'::text || cn.id) || '.created'::text) AS id,
    'contactNote.created'::text AS type,
    cn.date,
    co.company_id,
    cn.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    to_json(cn.*) AS contact_note,
    NULL::json AS deal_note
   FROM (public.contact_notes cn
     LEFT JOIN public.contacts co ON ((co.id = cn.contact_id)))
UNION ALL
 SELECT (('deal.'::text || d.id) || '.created'::text) AS id,
    'deal.created'::text AS type,
    d.created_at AS date,
    d.company_id,
    d.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    to_json(d.*) AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.deals d
UNION ALL
 SELECT (('dealNote.'::text || dn.id) || '.created'::text) AS id,
    'dealNote.created'::text AS type,
    dn.date,
    d.company_id,
    dn.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    to_json(dn.*) AS deal_note
   FROM (public.deal_notes dn
     LEFT JOIN public.deals d ON ((d.id = dn.deal_id)));


create or replace view "public"."companies_summary" as  SELECT c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    ( SELECT count(*) AS count
           FROM public.deals d
          WHERE (d.company_id = c.id)) AS nb_deals,
    ( SELECT count(*) AS count
           FROM public.contacts co
          WHERE (co.company_id = c.id)) AS nb_contacts
   FROM public.companies c;


create or replace view "public"."contacts_summary" as  SELECT co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'::jsonpath))::text AS email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'::jsonpath))::text AS phone_fts,
    c.name AS company_name,
    count(DISTINCT t.id) FILTER (WHERE (t.done_date IS NULL)) AS nb_tasks
   FROM ((public.contacts co
     LEFT JOIN public.tasks t ON ((co.id = t.contact_id)))
     LEFT JOIN public.companies c ON ((co.company_id = c.id)))
  GROUP BY co.id, c.name;


-- MANUALLY ADDED: the diff tool recreates views WITHOUT their grants and
-- WITHOUT security_invoker (this caused the 6 July 2026 production outage).
-- Restore both explicitly for the three recreated views.
alter view public.activity_log set (security_invoker = on);
alter view public.companies_summary set (security_invoker = on);
alter view public.contacts_summary set (security_invoker = on);

grant all on table public.activity_log to anon, authenticated, service_role;
grant all on table public.companies_summary to anon, authenticated, service_role;
grant all on table public.contacts_summary to anon, authenticated, service_role;

grant update on table "public"."companies" to "anon";

grant update on table "public"."companies" to "authenticated";

grant delete on table "public"."moneybird_company_contacts" to "service_role";

grant insert on table "public"."moneybird_company_contacts" to "service_role";

grant references on table "public"."moneybird_company_contacts" to "service_role";

grant select on table "public"."moneybird_company_contacts" to "service_role";

grant trigger on table "public"."moneybird_company_contacts" to "service_role";

grant truncate on table "public"."moneybird_company_contacts" to "service_role";

grant update on table "public"."moneybird_company_contacts" to "service_role";

grant delete on table "public"."moneybird_connections" to "service_role";

grant insert on table "public"."moneybird_connections" to "service_role";

grant references on table "public"."moneybird_connections" to "service_role";

grant select on table "public"."moneybird_connections" to "service_role";

grant trigger on table "public"."moneybird_connections" to "service_role";

grant truncate on table "public"."moneybird_connections" to "service_role";

grant update on table "public"."moneybird_connections" to "service_role";


-- MANUALLY ADDED: the default privileges (06_grants.sql) hand ALL on every new
-- table and sequence to anon/authenticated at CREATE time, and the diff tool
-- never emits the required revokes or column-level re-grants. The encrypted
-- token must never be readable by client roles: revoke everything and re-grant
-- SELECT on the non-secret columns only (api_token_encrypted omitted). The
-- moneybird_company_contacts cache is service-role-only.
revoke all on table public.moneybird_connections from anon, authenticated;
grant select (id, sales_id, administration_id, administration_name, created_at, updated_at)
    on table public.moneybird_connections to authenticated;
revoke all on table public.moneybird_company_contacts from anon, authenticated;

revoke all on sequence public.moneybird_connections_id_seq from anon, authenticated;
grant all on sequence public.moneybird_connections_id_seq to service_role;
revoke all on sequence public.moneybird_company_contacts_id_seq from anon, authenticated;
grant all on sequence public.moneybird_company_contacts_id_seq to service_role;

  create policy "Enable read access for connection owner"
  on "public"."moneybird_connections"
  as permissive
  for select
  to authenticated
using ((sales_id IN ( SELECT sales.id
   FROM public.sales
  WHERE (sales.user_id = ( SELECT auth.uid() AS uid)))));



