-- Gmail OAuth/API synchronization plus scheduled integration run support.
create table if not exists public.gmail_connections (
  id bigint generated by default as identity primary key,
  sales_id bigint not null references public.sales(id) on update cascade on delete cascade,
  email text not null,
  refresh_token_encrypted text not null,
  history_id text,
  sync_status text not null default 'connected'
    check (sync_status in ('connected', 'syncing', 'error')),
  last_synced_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists uq__gmail_connections__sales_id
  on public.gmail_connections using btree (sales_id);

create table if not exists public.gmail_oauth_states (
  state_hash text primary key,
  sales_id bigint not null references public.sales(id) on update cascade on delete cascade,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now()
);

alter table public.gmail_connections enable row level security;
alter table public.gmail_oauth_states enable row level security;

drop policy if exists "Enable read access for Gmail connection owner" on public.gmail_connections;
create policy "Enable read access for Gmail connection owner"
  on public.gmail_connections for select to authenticated
  using (sales_id in (
    select id from public.sales where user_id = (select auth.uid())
  ));

grant all on table public.gmail_connections to service_role;
revoke all on table public.gmail_connections from anon, authenticated;
grant select (id, sales_id, email, sync_status, last_synced_at, last_error, created_at, updated_at)
  on table public.gmail_connections to authenticated;

grant all on table public.gmail_oauth_states to service_role;
revoke all on table public.gmail_oauth_states from anon, authenticated;

grant all on sequence public.gmail_connections_id_seq to service_role;
revoke all on sequence public.gmail_connections_id_seq from anon, authenticated;

alter table public.integration_runs
  drop constraint if exists integration_runs_run_kind_check;
alter table public.integration_runs
  add constraint integration_runs_run_kind_check
  check (run_kind in ('manual', 'backfill', 'scheduled'));
