-- Sharing a status update as a link the client can simply open.
--
-- The body is stored as a SNAPSHOT: what the client received must keep saying
-- what it said, even after the deal moves on or someone edits the steps. The
-- token is the entire access credential for the public page, so it is long,
-- unique and revocable, and a row carries only the text that was sent - no
-- amounts, no internal notes.
create table if not exists public.deal_status_updates (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    company_id bigint,
    token text not null check (length(token) between 24 and 64),
    scope text not null default 'deal' check (scope in ('deal', 'company')),
    title text not null check (length(trim(title)) > 0),
    body text not null check (length(trim(body)) > 0),
    sections jsonb not null default '[]'::jsonb,
    company_name text,
    sender_name text,
    shared_by bigint,
    shared_at timestamp with time zone not null default now(),
    revoked_at timestamp with time zone,
    view_count integer not null default 0 check (view_count >= 0),
    last_viewed_at timestamp with time zone
);

create unique index if not exists uq__deal_status_updates__token
    on public.deal_status_updates using btree (token);
create index if not exists deal_status_updates_deal_shared_idx
    on public.deal_status_updates using btree (deal_id, shared_at desc);
create index if not exists deal_status_updates_company_shared_idx
    on public.deal_status_updates using btree (company_id, shared_at desc);
create index if not exists deal_status_updates_shared_by_idx
    on public.deal_status_updates using btree (shared_by);

alter table public.deal_status_updates
    drop constraint if exists deal_status_updates_deal_id_fkey;
alter table public.deal_status_updates
    add constraint deal_status_updates_deal_id_fkey foreign key (deal_id)
    references public.deals(id) on update cascade on delete cascade;

alter table public.deal_status_updates
    drop constraint if exists deal_status_updates_company_id_fkey;
alter table public.deal_status_updates
    add constraint deal_status_updates_company_id_fkey foreign key (company_id)
    references public.companies(id) on update cascade on delete set null;

alter table public.deal_status_updates
    drop constraint if exists deal_status_updates_shared_by_fkey;
alter table public.deal_status_updates
    add constraint deal_status_updates_shared_by_fkey foreign key (shared_by)
    references public.sales(id) on update cascade on delete set null;

alter table public.deal_status_updates enable row level security;

-- Visible to the team exactly as far as the deal itself is. The public page
-- never touches this table: it calls the status_update edge function, which runs
-- as service_role and resolves exactly one row by token. So there is
-- deliberately no anonymous policy - a leaked token opens one update, never the
-- table.
drop policy if exists "Enable read access for deal assignees" on public.deal_status_updates;
create policy "Enable read access for deal assignees" on public.deal_status_updates
    for select to authenticated
    using (deal_id in (select id from public.deals));

drop policy if exists "Enable insert for deal assignees" on public.deal_status_updates;
create policy "Enable insert for deal assignees" on public.deal_status_updates
    for insert to authenticated
    with check (public.is_active_crm_user() and deal_id in (select id from public.deals));

drop policy if exists "Enable revoke for deal assignees" on public.deal_status_updates;
create policy "Enable revoke for deal assignees" on public.deal_status_updates
    for update to authenticated
    using (deal_id in (select id from public.deals))
    with check (deal_id in (select id from public.deals));

grant all on table public.deal_status_updates to service_role;
revoke all on table public.deal_status_updates from anon, authenticated;
grant select on table public.deal_status_updates to authenticated;
grant insert (deal_id, company_id, token, scope, title, body, sections,
              company_name, sender_name, shared_by, shared_at)
    on table public.deal_status_updates to authenticated;
-- Revoking is the only change the team makes afterwards; the view counters
-- belong to the edge function.
grant update (revoked_at) on table public.deal_status_updates to authenticated;

grant all on sequence public.deal_status_updates_id_seq to service_role;
revoke all on sequence public.deal_status_updates_id_seq from anon, authenticated;
grant usage on sequence public.deal_status_updates_id_seq to authenticated;
